Add transfer hooks
thirdweb-dev/react pull request #116
Opened 2022-08-02 01:03 UTC by nachoiacovino

Updated the interface for Token so we can use the same one and it's the same one as the TS SDK

2022-08-02 20:25 UTC, jnsdls requested changes
couple of small changes

2022-08-02 20:25 UTC, jnsdls commented on src/types.ts
> -  to: WalletAddress;
does this not mean this becomes a breaking change? people would have to update their objects from `{to}` to `{toAddress}`?

I understand the change in itself but I don't think it's worth breaking inputs

2022-08-03 00:06 UTC, nachoiacovino commented on src/hooks/async/token.ts
> +export function useTransferBatchToken(contract: RequiredParam<Erc20>) {
felt better to maintaint the use-functioName-token structure, but I can change it if you feel strongly about it

2022-08-03 05:47 UTC, jnsdls requested changes

2022-08-03 05:47 UTC, jnsdls commented on src/types.ts
> +
let's merge this with tokenMintparams like you did but keep it `to` instead of `toAddress`

2022-08-03 17:40 UTC, jnsdls approved these changes
LGTM

2022-08-03 17:40 UTC, merged